### ISSUE TITLE
Keeping up with SQLite development  and special SQLite features?

### ISSUE THREAD

**Issue by Robert-M-Muench** [aergoio/litetree#14]
Some questions (maybe FAQ candidates) regarding the whole SQLite environment:

1. How actual is the SQLite engine in litetree? Can the SQLite code be updated manually to keep up with SQLite versions? Or are there are many patches necessary?
2. Are SQLite features like encryption, spital indexing extensions, etc. transparently supported?
3. Is it right, that the SQLite session extension could be completely replaced by litetree?

**Comment by kroggen** [comment]
Now it has SQLite 3.24.

I have not tried to use a patch. Probably the update will be made manually.

I guess that the update to the next SQLite version will occur only after the implementation of the new features.

Encryption is not supported by now, and for security reasons it should be implemented at the LMDB layer, to avoid identical pages stored. What could lead to cryptanalysis and maybe the discovery of the chosen key.

Spital index is new to me. Do you mean R-Tree? I have not tested it yet.

The session extension is used to merge changes between 2 separate database files. LiteTree works with a single database file that contains many versions inside.

**Comment by Robert-M-Muench** [comment]
Update: Ok, just don't fall to much behind ;-)

Encryption: I have used to official (payed) crypt support in SQLite. Works very well. Not sure how hard it is to get encryption into LMDB layer. This is a mandatory feature for us.

Spital index: Yes, R-Tree tables.

Session: We use it in a way that all the changesets are stored in the same database file. So, we just exclude the history table from tracking. Hence, all savepoints etc. are self-contained.

**Comment by Robert-M-Muench** [comment]
SQLite is now at 3.30. Is this project still alive?

**Comment by kroggen** [comment]
Hi,

I am really busy now developing a new product that will be released on the next month.

The update on LiteTree may happen on December.

If you need it before or other features, you can subscribe to a business support plan with our marketing team.

Best regards,
