### ISSUE TITLE
Doesn't work with sqlite3 ruby

### ISSUE THREAD

**Issue by zoras** [aergoio/litetree#15]
I tried `litetree` with [sqlite3 ruby](https://github.com/sparklemotion/sqlite3-ruby) gem which didn't work.

**Comment by kroggen** [comment]
Hi Saroj!

Have you used these commands specified on the repo?

> If you have sqlite3 installed in a non-standard location, you can specify the location of the include and lib files by doing:

```
gem install sqlite3 -- --with-sqlite3-include=/opt/local/include \
   --with-sqlite3-lib=/opt/local/lib
```

In the case of LiteTree it will be:

```
gem install sqlite3 -- --with-sqlite3-include=/usr/local/include \
   --with-sqlite3-lib=/usr/local/lib/litetree
```

To open the database we use a URI like this:

```
db = SQLite3::Database.new "file:test.db?branches=on"
```

Inform also the OS you are testing it and which were the results.

**Comment by kroggen** [comment]
OK, so the ruby wrapper is using LiteTree.

Maybe the wrapper could have executed some SQL commands internally, generating more commits before the `t1` table was created.

So we need to discover in which commit the `t1` table was created.

This can be achieved with the `PRAGMA branch_info(master)` just after creating the table.

Delete the database file before starting the new test.

After that you can create the `test` branch starting at that commit, or later, after inserting some rows to the table.

**Comment by zoras** [comment]
This works now. I think the `\n` while copy/pasting the test branch caused the error. I checked again and there were two branches with same `test` name.

* On Erroneous DB
```ruby
irb(main):037:0> db.execute "PRAGMA branches"
=> [["master"], ["test"], ["test"]]
```

* On Success
```ruby
~ ❯❯❯ irb
irb(main):001:0> require 'sqlite3'
=> true
irb(main):002:0> db = SQLite3::Database.new "file:test.db?branches=on"
=> #<SQLite3::Database:0x00007f862d902b98 @tracefunc=nil, @authorizer=nil, @encoding=nil, @busy_handler=nil, @collations={}, @functions={}, @results_as_hash=nil, @type_translation=nil, @readonly=false>
irb(main):003:0> db.execute "PRAGMA branch"
=> [["master"]]
irb(main):004:0> db.execute "CREATE TABLE t1 (name)"
=> []
irb(main):005:0> db.execute "PRAGMA branch_info(master)"
=> [["{\n\"total_commits\": 1\n}"]]
irb(main):006:0> db.execute "INSERT INTO t1 VALUES ('first')"
=> []
irb(main):007:0> db.execute "INSERT INTO t1 VALUES ('second')"
=> []
irb(main):008:0> db.execute "SELECT * FROM t1"
=> [["first"], ["second"]]
irb(main):009:0> db.execute "PRAGMA branch_info(master)"
=> [["{\n\"total_commits\": 3\n}"]]
irb(main):010:0> db.execute "PRAGMA new_branch=test at master.2"
=> []
irb(main):011:0> db.execute "PRAGMA branch_info(test)"
=> [["{\n\"source_branch\": \"master\",\n\"source_commit\": 2,\n\"total_commits\": 2\n}"]]
irb(main):012:0> db.execute "PRAGMA branch"
=> [["test"]]
irb(main):013:0> db.execute "PRAGMA branches"
=> [["master"], ["test"]]
irb(main):014:0> db.execute "INSERT INTO t1 VALUES ('from test branch')"
=> []
irb(main):015:0> db.execute "SELECT * FROM t1"
=> [["first"], ["from test branch"]]
irb(main):016:0> db.execute "PRAGMA branch=master"
=> []
irb(main):017:0> db.execute "SELECT * FROM t1"
=> [["first"], ["second"]]
irb(main):018:0> db.execute "PRAGMA branch_info(test)"
=> [["{\n\"source_branch\": \"master\",\n\"source_commit\": 2,\n\"total_commits\": 3\n}"]]
irb(main):019:0> db.execute "PRAGMA branch_info(master)"
=> [["{\n\"total_commits\": 3\n}"]]
irb(main):020:0> db.execute "PRAGMA branch=master.2"
=> []
irb(main):022:0> db.execute "SELECT * FROM t1"
=> [["first"]]
irb(main):023:0>
```

**Comment by zoras** [comment]
Glad to accidentally find the bug.

Also, I was wondering if it is possible to have threads/concurrent requests to `litetree` as it doesn't seem possible in `sqlite3` AFAIK.

**Comment by kroggen** [comment]
Yes, we can do it in SQLite as well. The database access will be serialized. Although I have not tested it in these conditions yet.

The bug is fixed.
