### ISSUE TITLE
Pruning of old commits / revisions

### ISSUE THREAD

**Issue by domob1812** [aergoio/litetree#16]
As far as I understand, litetree works by keeping copies of all versions of any changed database pages.  But that also means that the total storage requirement grows over time, particularly if the database is changed very often (even if the database itself does not grow), right?  Is there a way to tell litetree that some commit / old version is no longer needed and can be discarded (like checkpointing in SQLite's WAL mode)?

Particularly for blockchain applications (which seems to be the intent of litetree) this can be useful:  In order to handle chain reorgs, it is necessary to keep (persistent) snapshots of the last couple of states.  But as more and more blocks are added on top of an old one, it can be pruned eventually to save space.  (In some sense, revisions in litetree are like undo data in Bitcoin Core, which can (optionally) be pruned for old blocks.)

Perhaps my understanding is also completely wrong or this is already supported.  If so, please let me know.

**Comment by kroggen** [comment]
Hi Daniel,

I was researching exactly on this (merging commits) at this week.

Yes, it will be available on LiteTree. It may be released probably at this month.

**Comment by domob1812** [comment]
@kroggen:  Ok cool, thanks for the confirmation!  I believe this can be a very powerful feature (particularly for blockchain projects as ours and yours).

**Comment by kroggen** [comment]
Hi Daniel!

The support for [merging commits](https://github.com/aergoio/litetree/wiki/Merging-old-commits) is available in the [merge-commits](https://github.com/aergoio/litetree/tree/merge-commits) branch.

If you find any bug, please report it as a new issue.

**Comment by domob1812** [comment]
Thanks, good to know!
